# @package _global_

# run in debug mode with:
# `python run.py mode=debug`

hydra:
  # sets level of all command line loggers to 'DEBUG'
  verbose: True
  # sets output paths for all file logs to 'logs/debug/'
  run:
    dir: ${oc.env:DEBUG_DIR,debug}/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:DEBUG_DIR,./debug}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    n_jobs: 1

