save: '../save/ReacDiff/'
dt_save: 0.01
ini_time: 0.
fin_time: 1.
nx: 512
xL: 0.
xR: 1.
nu: 2.e0
rho: 1.e1
CFL: 2.5e-1
if_show: 1
numbers: 10000
if_second_order: 1.
show_steps: 100
init_key: 2022
if_rand_param: False