save: '../save/CFD/'
dt_save: 0.01
ini_time: 0.
fin_time: 1.
nx: 1024
ny: 1
nz: 1
xL: -1.
xR: 1.
yL: -1.
yR: 1.
zL: -1.
zR: 1.
bc: 'periodic'
gamma: 1.6666666666666667
eta: 1.e-2
zeta: 1.e-2
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 100
p_floor: 1.e-4
numbers: 1000
init_mode_Multi: '1D_rand'
init_key: 2022
if_rand_param: False
M0 : 0.