save: '../save/CFD/'
dt_save: 0.1
ini_time: 0.
fin_time: 2.
nx: 32
ny: 32
nz: 1
xL: 0.
xR: 1.
yL: 0.
yR: 1.
zL: 0.
zR: 1.
bc: 'KHI'
gamma: 1.6666666666666667
eta: 1.e-8
zeta: 1.e-8
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 100
p_floor: 1.e-4
numbers: 4
init_mode_Multi: 'KHs'
M0 : 0.1
dkMx: 2.
init_key: 2022