save: '../save/CFD/'
dt_save: 0.025
ini_time: 0.
fin_time: 0.5
nx: 256
ny: 256
nz: 256
xL: -1.
xR: 1.
yL: -1.
yR: 1.
zL: -1.
zR: 1.
bc: 'trans'
gamma: 1.6666666666666667
eta: 1.e-8
zeta: 1.e-8
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 400
p_floor: 1.e-4
init_mode: 'BlastWave'
M0: 1.
dk: 1.
dkMx: 1.
numbers: 4
init_mode_Multi: 'KHs'
init_key: 2022
