save: '../save/CFD/'
dt_save: 0.05
ini_time: 0.
fin_time: 1.
nx: 128
ny: 128
nz: 128
xL: 0.
xR: 1.
yL: 0.
yR: 1.
zL: 0.
zR: 1.
bc: 'periodic'
gamma: 1.6666666666666667
eta: 1.e-8
zeta: 1.e-8
CFL: 3.e-1
if_second_order: 1.
if_show: 1
show_steps: 400
p_floor: 1.e-4
numbers: 10
init_mode_Multi: '3D_rand'
M0 : 1.
k_tot: 4
init_key: 2022
if_rand_param: False