model_name: "FNO"
if_training: True
continue_training: False
num_workers: 2
batch_size: 50
initial_step: 10
t_train: 2
model_update: 2
filename: "2D_DarcyFlow_beta0.01_Train.hdf5"
single_file: True
reduced_resolution: 2
reduced_resolution_t: 1
reduced_batch: 1
epochs: 500
learning_rate: 1.e-3
scheduler_step: 100
scheduler_gamma: 0.5
#Unet
in_channels: 1
out_channels: 1
ar_mode: False
pushforward: False
unroll_step: 1
#FNO
num_channels: 1
modes: 12
width: 20
#Inverse
base_path: ../data/
training_type: autoregressive
#Inverse MCMC
mcmc_num_samples: 20
mcmc_warmup_steps: 10
mcmc_num_chains: 1
num_samples_max: 1000
in_channels_hid: 64
inverse_model_type: InitialConditionInterp
#Inverse grad
inverse_epochs: 100
inverse_learning_rate: 0.2
inverse_verbose_flag: False
