model_name: 'FNO'
if_training: False
continue_training: False
num_workers: 2
batch_size: 5
initial_step: 10
t_train: 101
model_update: 10
filename: '2D_diff-react_NA_NA'
single_file: False
reduced_resolution: 1
reduced_resolution_t: 1
reduced_batch: 1
epochs: 500
learning_rate: 1.e-3
scheduler_step: 100
scheduler_gamma: 0.5
#Unet
in_channels: 2
out_channels: 2
ar_mode: True
pushforward: True
unroll_step: 20
#FNO
num_channels: 2
modes: 12
width: 20
#Inverse
base_path: ../data/
training_type: autoregressive
#Inverse MCMC
mcmc_num_samples: 20
mcmc_warmup_steps: 10
mcmc_num_chains: 1
num_samples_max: 1000
in_channels_hid: 64
inverse_model_type: InitialConditionInterp    
#Inverse grad
inverse_epochs: 100
inverse_learning_rate: 0.2
inverse_verbose_flag: False
#Plotting
plot: False
channel_plot: 0 # Which channel/variable to be plotted
x_min: -1
x_max: 1
y_min: -1
y_max: 1
t_min: 0
t_max: 5