model_name: 'Unet'
if_training: True
continue_training: False
batch_size: 50
t_train: 30
model_update: 1
filename: 'ReacDiff_Nu0.5_Rho1.0.hdf5'
single_file: True
reduced_resolution: 4
reduced_resolution_t: 1
reduced_batch: 1
epochs: 500
learning_rate: 1.e-3
num_workers: 0
#Unet
in_channels: 1
out_channels: 1
ar_mode: True
pushforward: True
unroll_step: 10
#FNO
num_channels: 1
modes: 12
width: 20
scheduler_step: 100
scheduler_gamma: 0.5
initial_step: 5