save: '../save/advection/'
dt_save: 0.01
ini_time: 0.
fin_time: 2.
nx: 32
ny: 32
xL: 0.
xR: 1.
yL: 0.
yR: 1.
betaX : 1.e0
betaY : 1.e0
if_show: 1
numbers: 4
CFL: 2.5e-1
if_second_order: 1.
show_steps: 100
init_key: 2022
if_rand_param: False
